app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
*/

Route::get('setup/{step1?}', ['middleware' => 'setup', 'as' => 'setup', 'uses' => 'SetupController@getSetup']);
Route::post('setup/3', ['middleware' => 'setup','as' => 'create.account', 'uses' => 'SetupController@postSetupAccount']);
Route::post('setup/2', ['middleware' => 'setup', 'uses' => 'SetupController@postOvpnLogin']);
Route::post('setup/1', ['middleware' => 'setup', 'uses' => 'SetupController@postIntialSetup']);

Route::get('login', 'PagesController@getLogin');
Route::post('login', 'PagesController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::group(['middleware' => ['auth', 'language']], function () {
    Route::get('ovpn', ['as' => 'ovpn', 'uses' => 'PagesController@getOvpn']);
    Route::put('ovpn', 'PagesController@putOvpn');

    Route::get('wireless', ['as' => 'wireless', 'uses' => 'WirelessController@index']);
    Route::post('wireless', ['middleware' => 'auth', 'uses' => 'WirelessController@store']);

    Route::resource('/', 'DashboardController', ['as' => 'home', 'only' => ['index', 'store']]);
    Route::get('connection/{id}', 'DashboardController@show');
    Route::put('connection/{id}', 'DashboardController@update');
    Route::delete('connection/{id}', 'DashboardController@destroy');

    Route::resource('port', 'PortController', ['only' => ['index', 'store', 'destroy']]);

    Route::get('stats', 'StatisticsController@index');
    Route::get('stats/{id}/{interval}', 'StatisticsController@show');

    Route::resource('devices', 'DeviceController', ['only' => ['index', 'store', 'destroy', 'update']]);
    Route::group(['prefix' => 'devices'], function () {
        Route::put('{id}/move', 'DeviceController@moveDevice');
        Route::get('{id}/status', 'DeviceController@getStatus');
        Route::post('{id}/bypass', 'DeviceController@storeBypass');
        Route::delete('{id}/bypass', 'DeviceController@destroyBypass');
    });

    Route::resource('groups', 'GroupController', ['only' => ['destroy', 'update']]);

    Route::group(['prefix' => 'system'], function () {
        Route::get('/', ['as' => 'system', 'uses' => 'SystemController@index']);
        Route::post('reboot', 'SystemController@reboot');
        Route::post('poweroff', 'SystemController@poweroff');
    });

    Route::group(['prefix' => 'settings'], function () {
        Route::get('/', ['as' => 'settings.index', 'uses' => 'SettingsController@index']);
        Route::put('admin', ['as' => 'settings.admin', 'uses' => 'SettingsController@updateAccount']);
        Route::put('ovpn', ['as' => 'settings.ovpn', 'uses' => 'SettingsController@updateOvpn']);
    });
});

Route::get('demo', ['as' => 'test', 'uses' => 'PagesController@getDemo']);

app/Interfaces.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Interfaces extends Model
{
    protected $fillable = ['name', 'type'];

    /**
     * Each active interface has one group
     */
    public function group()
    {
        return $this->hasOne('App\Group');
    }

    /*
     * Each active interface has one connection
     */
    public function connection()
    {
        return $this->hasOne('App\Connection');
    }

    public function getConnectedAttribute()
    {
        if(file_exists('/tmp/' . $this->attributes['name'] . 'up')) {
            return true;
        }

        return false;
    }
}

resources/views/partials/group.blade.php
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading" style="min-height: 60px;">
                <div class="row">
                    <div class="col-sm-8">
                        <span class="group-title">{{ $group->name }}</span><br />
                        @if($group->adapter->connected)
                            @if(!is_null($group->connection()->active()->first()))
                                {{ $group->connection()->active()->first()->directives['event']['server'] }},
                                {{ $group->connection()->active()->first()->directives['event']['ip_info']['ip'] }},
                                {{ $group->connection()->active()->first()->directives['event']['ip_info']['ptr'] }}<br />
                                {{ $group->connection()->active()->first()->directives['event']['addon'] }},
                                <span id="{{ $group->adapter->name }}-hours">hh</span>:<span id="{{ $group->adapter->name }}-minutes">mm</span>:<span id="{{ $group->adapter->name }}-seconds">ss</span>
                            @else
                                {{ trans('dashboard.potential_bug') }}
                            @endif
                        @else
                            <span class="label label-danger">{{ trans('dashboard.disconnected') }}</span>
                        @endif
                    </div>
                    <div class="col-sm-4 text-right" style="margin-top: 13px;">
                        <button type="button" class="btn btn-default btn-sm reconnect" data-group="{{ $group->id }}" data-token="{{ csrf_token() }}">
                            {{ trans('dashboard.reconnect') }}
                        </button>&nbsp;
                        <button type="button" class="btn btn-default btn-sm disconnect" data-group="{{ $group->id }}" data-token="{{ csrf_token() }}">
                            {{ trans('dashboard.disconnect') }}</button>
                        &nbsp;
                        <button type="button" class="btn btn-default btn-sm show_log" data-group="{{ $group->id }}" data-adapter="{{ $group->adapter->name }}" data-token="{{ csrf_token() }}">
                            {{ trans('dashboard.show_log') }}
                        </button>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                @if($group->adapter->connected)
                    <div class="text-center">
                        <span style="color:#1EB300;margin-left: 10px;"><i class="fa fa-arrow-down"></i>&nbsp;<span id="{{ $group->adapter->name }}-input">-</span> Mbit/s</span>&nbsp;
                        <span style="color:#6D88AD"><i class="fa fa-arrow-up"></i>&nbsp;<span id="{{ $group->adapter->name }}-output">-</span> Mbit/s</span>
                    </div>
                    <div id="{{ $group->adapter->name }}" class="hidden-xs" style="min-width: 400px; height: 300px; margin: 0 auto"></div>
                @else
                    <h4 class="text-center" style="margin-bottom: 0px;">{{ trans('dashboard.connection_lost') }}</h4>
                    @if($group->connection()->active()->first()->directives['input']['killswitch'] == "active")
                        <p><strong>{{ trans('dashboard.calm_ks_activated') }}</strong></p>
                    @else
                        <p>{{ trans('dashboard.devices_normal_connection') }}</p>
                    @endif
                    <p>
                        {!! trans('dashboard.reconnect_or_disconnect') !!}
                    </p>
                @endif
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="{{ $group->adapter->name }}-openvpn" tabindex="-1" role="dialog" aria-labelledby="{{ $group->adapter->name }}-openvpn">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body" id="{{ $group->adapter->name }}-openvpn-body">

            </div>
        </div>
    </div>
</div>