app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
*/

Route::get('setup/{step1?}', ['middleware' => 'setup', 'as' => 'setup', 'uses' => 'SetupController@getSetup']);
Route::post('setup/3', ['middleware' => 'setup','as' => 'create.account', 'uses' => 'SetupController@postSetupAccount']);
Route::post('setup/2', ['middleware' => 'setup', 'uses' => 'SetupController@postOvpnLogin']);
Route::post('setup/1', ['middleware' => 'setup', 'uses' => 'SetupController@postIntialSetup']);

Route::get('login', 'PagesController@getLogin');
Route::post('login', 'PagesController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::group(['middleware' => ['auth', 'language']], function () {
    Route::get('ovpn', ['as' => 'ovpn', 'uses' => 'PagesController@getOvpn']);
    Route::put('ovpn', 'PagesController@putOvpn');

    Route::get('wireless', ['as' => 'wireless', 'uses' => 'WirelessController@index']);
    Route::post('wireless', ['middleware' => 'auth', 'uses' => 'WirelessController@store']);

    Route::resource('/', 'DashboardController', ['as' => 'home', 'only' => ['index', 'store']]);
    Route::get('connection/{id}', 'DashboardController@show');
    Route::put('connection/{id}', 'DashboardController@update');
    Route::delete('connection/{id}', 'DashboardController@destroy');

    Route::resource('port', 'PortController', ['only' => ['index', 'store', 'destroy']]);

    Route::get('stats', 'StatisticsController@index');
    Route::get('stats/{id}/{interval}', 'StatisticsController@show');

    Route::resource('devices', 'DeviceController', ['only' => ['index', 'store', 'destroy', 'update']]);
    Route::group(['prefix' => 'devices'], function () {
        Route::put('{id}/move', 'DeviceController@moveDevice');
        Route::get('{id}/status', 'DeviceController@getStatus');
        Route::post('{id}/bypass', 'DeviceController@storeBypass');
        Route::delete('{id}/bypass', 'DeviceController@destroyBypass');
    });

    Route::resource('groups', 'GroupController', ['only' => ['destroy', 'update']]);

    Route::group(['prefix' => 'system'], function () {
        Route::get('/', ['as' => 'system', 'uses' => 'SystemController@index']);
        Route::post('reboot', 'SystemController@reboot');
        Route::post('poweroff', 'SystemController@poweroff');
    });

    Route::group(['prefix' => 'settings'], function () {
        Route::get('/', ['as' => 'settings.index', 'uses' => 'SettingsController@index']);
        Route::put('admin', ['as' => 'settings.admin', 'uses' => 'SettingsController@updateAccount']);
        Route::put('ovpn', ['as' => 'settings.ovpn', 'uses' => 'SettingsController@updateOvpn']);
    });
});

Route::get('demo', ['as' => 'test', 'uses' => 'PagesController@getDemo']);

app/Port.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Port extends Model
{
    protected $fillable = ['device_id', 'start', 'end', 'type'];

    /**
     * Get the phone record associated with the user.
     */
    public function device()
    {
        return $this->belongsTo('App\Device');
    }

    public function getRangeAttribute()
    {
        if($this->attributes['start'] ==  $this->attributes['end']) {
            return $this->attributes['start'];
        }

        return $this->attributes['start'] . ' - ' . $this->attributes['end'];
    }

    public function getTypeAttribute($value)
    {
        if($value == '1') {
            return 'TCP';
        } elseif($value == '2') {
            return 'UDP';
        } else {
            return 'TCP/UDP';
        }
    }

    public function getConfigTypeAttribute()
    {
        if($this->attributes['type'] == '1') {
            return 'tcp';
        } elseif($this->attributes['type'] == '2') {
            return 'udp';
        } else {
            return 'both';
        }
    }
}

resources/views/pages/dashboard.blade.php
@extends('master')

@section('content')

<div class="row @if($connected->isEmpty()) hidden @endif">
    <div class="col-sm-12">
        <div class="pull-right">
            <button type="button" id="show_connection" class="btn btn-primary"><i class="fa fa-plus"></i> {{ trans('dashboard.new_connection') }}</button>
            <button type="button" id="hide_connection" class="btn btn-primary hidden"><i class="fa fa-minus"></i> {{ trans('dashboard.hide') }}</button>
            <br /><br />
        </div>
    </div>
</div>
<div class="row form_connection @if(!$connected->isEmpty()) hidden @endif">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title" style="color: #3B88B6;font-weight: 400;">{{ trans('dashboard.new_connection') }}</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    @if($disconnected->isEmpty())
                        <div class="col-sm-12">
                            <div class="alert alert-info" role="alert">{{ trans('dashboard.all_groups_connected') }}</div>
                        </div>
                    @else
                        <div class="col-sm-6">
                            <div class="choose-server">
                                <form role="form" method="post" action="#" id="connect">
                                    <div class="form-group">
                                        <select class="form-control" id="group">
                                            @foreach($disconnected as $group)
                                                <option value="{{ $group->id }}">{{ $group->name }} @if(!$group->hidden) - {{ $group->devices->count() }} @if($group->devices->count() == 1) {{ trans('dashboard.device') }} @else {{ trans('dashboard.devices') }} @endif @endif</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <select class="form-control" id="connection_type">
                                            <option value="auto">{{ trans('dashboard.choose_best_server_auto') }}</option>
                                            <option value="DE">{{ trans('dashboard.choose_best_server_de') }}</option>
                                            <option value="SE">{{ trans('dashboard.choose_best_server_se') }}</option>
                                            <option value="manual">{{ trans('dashboard.choose_manual') }}</option>
                                        </select>
                                    </div>
                                    <div class="form-group hidden">
                                        <select class="form-control" id="server_ip">
                                            @if($servers)
                                                @foreach($servers as $server)
                                                    <option value="{{ $server->ip }}">{{ $server->name }}</option>
                                                @endforeach
                                            @else
                                                <option value="0">{{ trans('dashboard.techinical_error') }}</option>
                                            @endif
                                        </select>
                                    </div>
                                    <!-- Denna select meny visas och är populerad med tilläggstjänsterna som är aktiva. Om inga tilläggstjänster finns är den dold. -->
                                    <div class="choose-addon form-group @if(!$ovpn->addons) hidden @endif">
                                        <select class="form-control" id="addon">
                                            <option value="normal" selected>{{ trans('dashboard.no_addon') }}</option>
                                            @if($ovpn->addons)
                                                @foreach($ovpn->addons as $addon) {
                                                <option value="{{ $addon }}">{{ \App\Services\Helpers\String::addonAbbreviationToText($addon) }}</option>
                                                @endforeach
                                            @endif
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <select class="form-control" id="killswitch">
                                            <option value="active">{{ trans('dashboard.activate_killswitch') }}</option>
                                            <option value="inactive">{{ trans('dashboard.inactivate_killswitch') }}</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <button type="submit" name="submit" class="btn btn-primary submit">{{ trans('dashboard.connect') }}</button>
                                    </div>
                                    {{ csrf_field() }}
                                </form>
                            </div>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

@if(!$connected->isEmpty())
    @foreach($connected as $group)
        @include('partials.group', ['group' => $group])
        <script>
            var {{ $group->adapter->name }}, {{ $group->adapter->name }}_uptime = 0;
            $(document).ready(function() {

                Highcharts.setOptions({
                    global : {
                        timezoneOffset: -120
                    }
                });

                {{ $group->adapter->name }} = new Highcharts.Chart({
                    chart: {
                        defaultSeriesType: 'areaspline',
                        renderTo: '{{ $group->adapter->name }}'
                    },
                    tooltip: {
                        formatter: function () {
                            var s = '<b>' + new Date(this.x).toLocaleString() + '</b>', val = 0;

                            $.each(this.points, function () {
                                if(this.y < 0) {
                                    val = (this.y*-1);
                                } else {
                                    val = this.y;
                                }

                                s += '<br/><span style="color:' + this.series.color + '">•</span> ' + this.series.name + ': ' +
                                        val.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ' ');
                            });

                            return s;
                        },
                        shared: true
                    },
                    rangeSelector: {
                        enabled: false
                    },
                    navigator: {
                        enabled: false
                    },
                    scrollbar: {
                        enabled: false
                    },
                    title: {
                        text: null
                    },
                    yAxis: {
                        title: {
                            text: null
                        }
                    },
                    xAxis: {
                        type: 'datetime'
                    },
                    series : [{
                        name : '{{ trans('dashboard.download_speed') }}',
                        color: '#1EB300',
                        fillOpacity: 0.2,
                        data : (function () {
                            var data = [], time = (new Date()).getTime(), i;
                            var dataLength = 299;

                            // display speed values for each 2 second
                            for (i = -1*dataLength; i <= 0; i += 1) {
                                data.push([
                                    time + i * 2000,
                                    0
                                ]);
                            }
                            return data;
                        }())
                    },{
                        name : '{{ trans('dashboard.upload_speed') }}',
                        color: '#6D88AD',
                        fillOpacity: 0.2,
                        data : (function () {
                            var data = [], time = (new Date()).getTime(), i;
                            var dataLength = 299;

                            // display speed values for each 2 second
                            for (i = -1*dataLength; i <= 0; i += 1) {
                                data.push([
                                    time + i * 2000,
                                    0
                                ]);
                            }
                            return data;
                        }())
                    }
                    ]
                });
            });
        </script>
    @endforeach
@endif
@endsection

resources/views/pages/devices.blade.php
@extends('master')

@section('content')

<div class="group-list" data-token="{{ csrf_token() }}" data-groups='{!! json_encode($groups->toArray()) !!}'>
    @if(!$groups->isEmpty())
        @foreach($groups as $group)
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-heading" style="min-height: 60px;">
                            <div class="row">
                                <div class="col-sm-8">
                                    <span id="group-{{ $group->id }}"><span id="group-{{ $group->id }}-container" class="group-title">{{ $group->name }}</span><br /></span>
                                    @if($group->adapter['connected'])
                                        @if(!is_null($group->connection()->active()->first()))
                                            {{ $group->connection()->active()->first()->directives['event']['server'] }},
                                            {{ $group->connection()->active()->first()->directives['event']['addon'] }},
                                            <span id="{{ $group->adapter->name }}-hours">hh</span>:<span id="{{ $group->adapter->name }}-minutes">mm</span>:<span id="{{ $group->adapter->name }}-seconds">ss</span>,  
                                            {{ $group->traffic_download }} GB /   {{ $group->traffic_upload }} GB
                                            <script>var {{ $group->adapter->name }}, {{ $group->adapter->name }}_uptime = 0;</script>
                                        @else
                                            {{ trans('devices.potential_bug') }}
                                        @endif
                                    @else
                                        <span class="label label-danger">{{ trans('devices.disconnected') }}</span>
                                    @endif
                                </div>
                                <div class="col-sm-4 text-right" style="margin-top: 13px;">
                                    <a href="#" class="rename_group" data-group="{{ $group->id }}">
                                        <i class="fa fa-pencil-square-o"></i>
                                    </a>
                                    @if(!$group->adapter['connected'])
                                        <a href="#" class="delete_group" data-group="{{ $group->id }}">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="alert alert-info no-devices-{{ $group->id }} @if(!$group->devices->isEmpty()) hidden @endif" role="alert" style="margin-bottom: 0;">{{ trans('devices.no_devices_in_group') }}</div>
                            <table class="table table-hover group-{{ $group->id }} @if($group->devices->isEmpty()) hidden @endif" data-count="{{ $group->devices->count() }}">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>{{ trans('devices.name') }}</th>
                                        <th>{{ trans('devices.ip') }}</th>
                                        <th>{{ trans('devices.mac_address') }}</th>
                                        <th>{{ trans('devices.status') }}</th>
                                        <th>{{ trans('devices.handle') }}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @if(!$group->devices->isEmpty())
                                    @foreach($group->devices as $x => $device)
                                        <tr class="device-{{ $device->id }}">
                                            <th scope="row">{{ ($x+1) }}</th>
                                            <td>
                                                <span id="device-{{ $device->id }}-container">{{ $device->name }}</span>
                                            </td>
                                            <td>{{ $device->ip }}</td>
                                            <td>{{ $device->mac }}</td>
                                            <td id="connectivity-{{ $device->id }}"><i class="fa fa-cog fa-spin"></i></td>
                                            <td>
                                                <a href="javascript:void(0);" class="rename_device" title="{{ trans('devices.rename_device') }}"
                                                   data-device="{{ $device->id }}" data-name="{{ $device->name }}"><i class="fa fa-pencil"></i></a>
                                                <a href="javascript:void(0);" class="deactivate_bypass {{ $device->id }}-deactivate @if(!$device->bypass) hidden @endif"
                                                   title="{{ trans('devices.activate_protection') }}" data-device="{{ $device->id }}"><i class="fa fa-unlock"></i></a>
                                                <a href="javascript:void(0);" class="activate_bypass {{ $device->id }}-activate @if($device->bypass) hidden @endif"
                                                   title="{{ trans('devices.deactivate_protection') }}" data-device="{{ $device->id }}"><i class="fa fa-lock"></i></a>
                                                <a href="javascript:void(0);" class="move_device" title="{{ trans('devices.move_device') }}"
                                                   data-device="{{ $device->id }}" data-name="{{ $device->name }}" data-group="{{ $group->id }}"><i class="fa fa-group"></i></a>
                                                <a href="javascript:void(0);" class="delete_device" title="{{ trans('devices.delete_device') }}"
                                                   data-device="{{ $device->id }}"><i class="fa fa-trash"></i></a>
                                            </td>
                                        </tr>
                                    @endforeach
                                @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    @endif
</div>

<h4>{{ trans('devices.unsorted_devices') }}
    @if(!is_null($hidden))
        <br />
        <span style="color:#333;font-size:13px;">  
            @if($hidden->adapter->connected)
                {{ $hidden->connection()->active()->first()->directives['event']['server'] }},
                {{ $hidden->connection()->active()->first()->directives['event']['addon'] }},
                <span id="{{ $hidden->adapter->name }}-hours">hh</span>:<span id="{{ $hidden->adapter->name }}-minutes">mm</span>:<span id="{{ $hidden->adapter->name }}-seconds">ss</span>,  
                {{ $hidden->traffic_download }} GB /   {{ $hidden->traffic_upload }} GB
            @else
                <span class="label label-danger">{{ trans('devices.disconnected') }}</span>
            @endif
                          </span>
        <script>var {{ $hidden->adapter->name }}, {{ $hidden->adapter->name }}_uptime = 0;</script>
    @endif
</h4>

<div class="alert alert-info @if(!empty($unsorted)) hidden @endif dynamicips-none" role="alert">{{ trans('devices.all_devices_sorted') }}</div>
<table class="@if(empty($unsorted)) hidden @endif dynamicips table table-hover" data-count="{{ count($unsorted) }}">
    <thead>
    <tr>
        <th>#</th>
        <th width="100">{{ trans('devices.name') }}</th>
        <th width="100">{{ trans('devices.ip') }}</th>
        <th width="100">{{ trans('devices.mac_address') }}</th>
        <th>{{ trans('devices.handle') }}</th>
    </tr>
    </thead>
    <tbody>
        @if(!empty($unsorted))
            @foreach($unsorted as $x => $device)
                <form method="post" data-id="{{ $x }}" class="form-inline devicegroup">
                    <tr class="unsorted-{{ $x }}">
                        <th scope="row">{{ ($x+1) }}</th>
                        <td width="100">
                            <div class="form-group">
                                <input type="text" class="form-control" name="device" id="device{{ $x }}" value="@if(isset($device['hostname'])){{ $device['hostname'] }}@else {{ trans('devices.unknown') }} @endif">
                            </div>
                        </td>
                        <td width="100">{{ $device['ip'] }}</td>
                        <td width="100">@if(isset($device['mac'])) {{ $device['mac'] }} @else - @endif</td>
                        <td>
                            <div class="form-group">
                                <select name="group" id="group{{ $x }}" class="form-control">
                                    @if(!$groups->isEmpty())
                                        <option value="choose">{{ trans('devices.choose_group') }}</option>
                                        @foreach($groups as $group)
                                            <option value="{{ $group->id }}">{{ $group->name }}</option>
                                        @endforeach
                                    @endif
                                        <option value="create">{{ trans('devices.create_group') }}</option>
                                </select>
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <input type="hidden" name="mac" id="mac{{ $x }}" value="{{ $device['mac'] }}" />
                                <input type="hidden" name="token" id="token{{ $x }}" value="{{ csrf_token() }}" />
                                <input type="submit" class="btn btn-primary" id="submit{{ $x }}" value="{{ trans('devices.save') }}" />
                            </div>
                        </td>
                    </tr>
                </form>
            @endforeach
        @endif
    </tbody>
</table>


<!-- Modal -->
<div class="modal fade" id="deviceModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modalTitle"></h4>
            </div>
            <div class="modal-body" id="modalBody">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="info-move alert alert-info hidden"></div>
                        <form class="move-device-form form-horizontal">
                            <div class="form-group">
                                <input type="hidden" id="device-move" value="">
                                <select id="groups-move" class="form-control">

                                </select>
                            </div>
                            <div class="form-group">
                                <button type="button" class="btn btn-default" data-dismiss="modal">{{ trans('devices.cancel') }}</button>
                                <button type="submit" class="btn btn-primary submit">{{ trans('devices.move') }}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        @foreach($devices as $device)
            checkConnectivity({{ $device->id }});
        @endforeach
    });
</script>
@endsection

resources/views/pages/ovpn.blade.php
@extends('master')

@section('content')

<h4>
    <span class="pull-left" style="margin-bottom: 30px;">{{ trans('ovpn.account') }}</span>
    <span class="pull-right">
        <a href="javascript:void(0);" class="reload_settings" title="{{ trans('ovpn.refresh_account') }}" data-token="{{ csrf_token() }}"><i class="fa fa-refresh"></i>
        </a>
    </span>
</h4>
<table class="table table-hover">
    <tbody>
    <tr>
        <td>{{ trans('ovpn.username') }}</td>
        <td>{{ $account->username }}</td>
    </tr>
    <tr>
        <td>{{ trans('ovpn.subscription') }}</td>
        <td>{{ $account->default }}</td>
    </tr>
    <tr>
        <td>{{ trans('ovpn.filtration') }}</td>
        <td>{{ $account->filtering }}</td>
    </tr>
    <tr>
        <td>{{ trans('ovpn.public_ipv4') }}</td>
        <td>{{ $account->public_ipv4 }}</td>
    </tr>
    <tr>
        <td>{{ trans('ovpn.multihop') }}</td>
        <td>{{ $account->multihop }}</td>
    </tr>
    </tbody>
</table>

<h4>{{ trans('ovpn.datacenters') }}</h4>
<table class="table table-hover">
    <tbody>
        @foreach($datacenters['datacenters'] as $datacenter)
            <tr>
                <td>{{ $datacenter->city }}, {{ $datacenter->country }}</td>
                <td>{{ $datacenter->hops }} {{ trans('ovpn.hops') }} - {{ $datacenter->ping }} {{ trans('ovpn.latency') }}</td>
            </tr>
        @endforeach
    </tbody>
</table>

<h4>{{ trans('ovpn.top_servers') }}</h4>
<table class="table table-hover">
    <tbody>
    @foreach($servers as $server)
        <tr>
            <td>{{ $server->name }}</td>
            <td>{{ $server->currentLoad->bandwidth }}% {{ trans('ovpn.load') }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

@endsection

resources/views/pages/port.blade.php
@extends('master')

@section('content')

    <h4>{{ trans('port.portforwarding') }}</h4>

    <div class="alert alert-info ports-display @if(!$ports->isEmpty()) hidden @endif" role="alert">{{ trans('port.no_portforwards') }}
    </div>
    <table class="table table-hover @if($ports->isEmpty()) hidden @endif">
        <thead>
        <tr>
            <th>{{ trans('port.device') }}</th>
            <th>{{ trans('port.port_range') }}</th>
            <th>{{ trans('port.type') }}</th>
            <th>{{ trans('port.handle') }}</th>
        </tr>
        </thead>
        <tbody id="port-list">
        @if(!$ports->isEmpty())
            @foreach($ports as $port)
                <tr id="port-{{ $port->id }}">
                    <td>{{ $port->device->name }}
                        <small>({{ $port->device->ip }})</small>
                    </td>
                    <td>{{ $port->range }}</td>
                    <td>{{ $port->type }}</td>
                    <td>
                        <a href="javascript:void(0);" class="delete_port" title="{{ trans('port.remove_port_forward') }}"
                           data-portid="{{ $port->id }}"><i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
            @endforeach
        @endif
        </tbody>
    </table>
    <br/><br/>
    <h4>{{ trans('port.new_portforward') }}</h4>
    @if($devices->isEmpty())
        <div class="alert alert-info" role="alert">{!! trans('port.require_static_ip') !!}</div>
    @else
        <form role="form" class="form-inline" id="port_form" method="post">
            {{ csrf_field() }}
            <div class="form-group">
                <select class="form-control" name="device" id="device">
                    @foreach($devices as $device)
                        <option value="{{ $device->id }}">{{ $device->name }} - {{ $device->ip }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <div class="input-group" style="width:180px;">
                    <input type="text" class="form-control" id="port_number_1" name="port_number_1" placeholder="Port"/>
                    <div class="input-group-addon">-</div>
                    <input type="text" class="form-control" id="port_number_2" name="port_number_2" placeholder="Port"/>
                </div>
            </div>
            <div class="form-group">
                <select class="form-control" name="protocol" id="protocol">
                    <option value="1">TCP</option>
                    <option value="2">UDP</option>
                    <option value="3">TCP/UDP</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="{{ trans('port.open_port') }}" />
            </div>
        </form>
    @endif
    <br/><br/>
    <h4>OVPN</h4>
    @if(is_null($account->ports))
        <div class="alert alert-info" role="alert">
            @if(is_null($account->public_ipv4))
                {{ trans('port.no_open_ports') }}
            @else
                {{ trans('port.no_open_ports_public_ipv4') }}
            @endif
        </div>
    @else
        <table class="table table-hover">
            <thead>
            <tr>
                <th>{{ trans('port.port') }}</th>
                <th>{{ trans('port.type') }}</th>
            </tr>
            </thead>
            <tbody>
                @foreach($account->ports as $port)
                    <tr>
                        <td>
                            {{ $port['port'] }}
                        </td>
                        <td>
                            @if($port['type'] == 'both')
                                TCP/UDP
                            @else
                                {{ strtoupper($port['type']) }}
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif
@endsection